### ISSUE TITLE
Bug: 导入的 xss 包不支持浏览器端，导致页面无法正常加载

### ISSUE THREAD

**Issue by ifrvn** [shigma/marked-vue#1]
## 问题描述

使用 koishi `pnpm run dev` 后，打开控制台页面出现白屏，查看报错：

![L@XKWU1 2SXOW$PTUD3(K%3](https://user-images.githubusercontent.com/21982381/212540294-cf0ee4cd-5271-4481-921e-9807075d4d11.jpg)

![HAQS_)0 (VAA8AKI3~RHG_2](https://user-images.githubusercontent.com/21982381/212540302-8787ed4c-2468-4ae5-9494-10f67ab861a7.jpg)

## 相关版本

- koishi 4.11.2
- @koishijs/plugin-console 5.1.6
- marked-vue 1.1.1

## 其他信息

或许应该使用`import * as xss from 'xss/dist/xss.js';`

**Comment by shigma** [comment]
已修复，感谢反馈。
